import path from "path";
import { fileURLToPath } from "url";
import { WithLinariaConfig } from "./types";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export function addTurbopackConfig(config: WithLinariaConfig) {
  config.turbopack ??= {};
  config.turbopack.rules ??= {};

  const transformLoaderPath = path.resolve(__dirname, "./loaders/turbopackTransformLoader.mjs");
  const cssLoaderPath = path.resolve(__dirname, "./loaders/cssLoader.mjs");

  const transformLoader = {
    loader: transformLoaderPath,
    options: {},
  };

  const cssLoader = {
    loader: cssLoaderPath,
    options: {},
  };

  // config.turbopack.rules["*.{ts,tsx,js,jsx}"] = {
  config.turbopack.rules["*.tsx"] = {
    condition: {
      // TODO: can be removed once https://github.com/vercel/next.js/issues/79592 is fixed
      not: { path: /middleware\.(tsx?|jsx?)$/ },
    },
    loaders: [transformLoader],
  };

  // Add a loader for the noop CSS files generated by the Transformer
  // This ensures the CSS content is properly resolved when turbopack encounters imports like:
  // import "../../../../packages/next/style-this.module.css?filepath=..."
  config.turbopack.rules["*.module.css"] = {
    loaders: [cssLoader],
  };

  config.turbopack.rules["*.global.css"] = {
    loaders: [cssLoader],
  };

  return config;
}
